import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  AlertTriangle, 
  ExternalLink, 
  CheckCircle, 
  XCircle,
  Info
} from "lucide-react";

export default function ConnectionNotice() {
  const openWhatsAppWeb = () => {
    window.open('https://web.whatsapp.com', '_blank');
  };

  return (
    <div className="space-y-4">
      {/* Important Notice */}
      <Alert className="border-orange-200 bg-orange-50">
        <AlertTriangle className="h-4 w-4 text-orange-600" />
        <AlertDescription className="text-orange-800">
          <strong>Important:</strong> The phone codes generated by this app are demonstration codes only. 
          They cannot connect to real WhatsApp because only WhatsApp's official servers can create authentic linking codes.
        </AlertDescription>
      </Alert>

      {/* Feature Status */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Info className="w-5 h-5" />
            Current App Status
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className="flex items-center justify-between">
              <span>AI Chatbot System</span>
              <Badge variant="default" className="bg-green-100 text-green-800 flex items-center gap-1">
                <CheckCircle className="w-3 h-3" />
                Working
              </Badge>
            </div>
            
            <div className="flex items-center justify-between">
              <span>Message Templates</span>
              <Badge variant="default" className="bg-green-100 text-green-800 flex items-center gap-1">
                <CheckCircle className="w-3 h-3" />
                Working
              </Badge>
            </div>
            
            <div className="flex items-center justify-between">
              <span>Contact Management</span>
              <Badge variant="default" className="bg-green-100 text-green-800 flex items-center gap-1">
                <CheckCircle className="w-3 h-3" />
                Working
              </Badge>
            </div>
            
            <div className="flex items-center justify-between">
              <span>Campaign Planning</span>
              <Badge variant="default" className="bg-green-100 text-green-800 flex items-center gap-1">
                <CheckCircle className="w-3 h-3" />
                Working
              </Badge>
            </div>
            
            <div className="flex items-center justify-between">
              <span>Real WhatsApp Connection</span>
              <Badge variant="secondary" className="bg-red-100 text-red-800 flex items-center gap-1">
                <XCircle className="w-3 h-3" />
                Limited
              </Badge>
            </div>
            
            <div className="flex items-center justify-between">
              <span>Phone Code Linking</span>
              <Badge variant="secondary" className="bg-red-100 text-red-800 flex items-center gap-1">
                <XCircle className="w-3 h-3" />
                Demo Only
              </Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Working Solutions */}
      <Card>
        <CardHeader>
          <CardTitle>Real WhatsApp Solutions</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-3">
            <div className="border rounded-lg p-4">
              <h4 className="font-semibold mb-2">Option 1: Use Official WhatsApp Web</h4>
              <p className="text-sm text-gray-600 mb-3">
                Use the official WhatsApp Web alongside this app for real messaging capabilities.
              </p>
              <Button onClick={openWhatsAppWeb} variant="outline" size="sm">
                <ExternalLink className="w-4 h-4 mr-2" />
                Open WhatsApp Web
              </Button>
            </div>
            
            <div className="border rounded-lg p-4">
              <h4 className="font-semibold mb-2">Option 2: WhatsApp Business API</h4>
              <p className="text-sm text-gray-600 mb-3">
                Apply for official WhatsApp Business API access from Meta for real integration.
              </p>
              <Badge variant="outline">Paid Solution</Badge>
            </div>
            
            <div className="border rounded-lg p-4">
              <h4 className="font-semibold mb-2">Option 3: Manual Message Management</h4>
              <p className="text-sm text-gray-600 mb-3">
                Use this app to create templates and manage contacts, then manually send messages through WhatsApp.
              </p>
              <Badge variant="outline">Free Solution</Badge>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* What Works Now */}
      <Alert className="border-blue-200 bg-blue-50">
        <CheckCircle className="h-4 w-4 text-blue-600" />
        <AlertDescription className="text-blue-800">
          <strong>Good News:</strong> All other features work perfectly! You can create campaigns, 
          manage contacts, use AI chatbots, and prepare everything for when you have real WhatsApp access.
        </AlertDescription>
      </Alert>
    </div>
  );
}